services:
  app1:
    container_name: app1
    build:
      context: .
      dockerfile: Dockerfile

  app2:
    container_name: app2
    build:
      context: .
      dockerfile: Dockerfile

  app3:
    container_name: app3
    build:
      context: .
      dockerfile: Dockerfile

  app4:
    container_name: app4
    build:
      context: .
      dockerfile: Dockerfile

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres: